//
//  CsuExtractScript.js
//  LightTable
//
//  Created by 空白 on 2026/6/16.
// generated by codex

(() => {
    function cleanText(value) {
      return (value || "")
        .replace(/\u00a0/g, " ")
        .replace(/\s+/g, " ")
        .trim();
    }

    function expandRange(start, end, parity) {
      const result = [];
      for (let i = start; i <= end; i++) {
        if (parity === "odd" && i % 2 === 0) continue;
        if (parity === "even" && i % 2 !== 0) continue;
        result.push(i);
      }
      return result;
    }

    function parseWeeks(text) {
      const raw = cleanText(text);
      if (!raw) return [];

      const parity = raw.includes("单") ? "odd" : raw.includes("双") ? "even" : "all";
      const rangeText = raw
        .replace(/[（(].*?[）)]/g, "")
        .replace(/周/g, "");

      const weeks = [];

      rangeText.split(/[,\，、]/).forEach(part => {
        const token = cleanText(part);
        if (!token) return;

        const rangeMatch = token.match(/^(\d+)\s*[-－~～]\s*(\d+)$/);
        if (rangeMatch) {
          weeks.push(...expandRange(Number(rangeMatch[1]), Number(rangeMatch[2]), parity));
          return;
        }

        const singleMatch = token.match(/^(\d+)$/);
        if (singleMatch) {
          const week = Number(singleMatch[1]);
          if (parity === "odd" && week % 2 === 0) return;
          if (parity === "even" && week % 2 !== 0) return;
          weeks.push(week);
        }
      });

      return [...new Set(weeks)].sort((a, b) => a - b);
    }

    function parsePeriods(text) {
      const nums = cleanText(text).match(/\d+/g) || [];
      if (nums.length === 0) return [];

      const start = Number(nums[0]);
      const end = Number(nums[nums.length - 1]);

      const result = [];
      for (let i = start; i <= end; i++) {
        result.push(i);
      }
      return result;
    }

    function parseCourseDiv(div) {
      const courses = [];
      let current = null;

      function pushCurrent() {
        if (current && current.name) {
          courses.push(current);
        }
        current = null;
      }

      div.childNodes.forEach(node => {
        if (node.nodeType === Node.TEXT_NODE) {
          const text = cleanText(node.textContent);
          if (!text) return;

          if (!current || current.weekText || current.teacher || current.location) {
            pushCurrent();
            current = { name: text };
          } else {
            current.name += text;
          }
          return;
        }

        if (node.nodeType !== Node.ELEMENT_NODE) return;

        const title = node.getAttribute("title") || "";
        const value = cleanText(node.textContent);
        if (!value) return;

        if (!current) current = { name: "" };

        if (title.includes("老师")) {
          current.teacher = value;
        } else if (title.includes("周次")) {
          current.weekText = value;
          current.weekInterval = parseWeeks(value);
        } else if (title.includes("教室")) {
          current.location = value;
        }
      });

      pushCurrent();
      return courses;
    }

    function hasCourseContent(div) {
      const text = cleanText(div.textContent);
      return text && text !== "&nbsp;";
    }

    const tables = Array.from(document.querySelectorAll("table"));

    const scheduleTable = tables.find(table => {
      const headerText = cleanText(table.rows[0]?.textContent);
      return headerText.includes("星期日") &&
        headerText.includes("星期一") &&
        headerText.includes("星期六");
    });

    if (!scheduleTable) {
      return JSON.stringify({
        error: "未找到课表表格"
      });
    }

    const weekdayMap = [1, 2, 3, 4, 5, 6, 7];
    const weekdayNames = ["星期日", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六"];

    const courses = [];

    Array.from(scheduleTable.rows).slice(1).forEach(row => {
      const periodText = cleanText(row.cells[0]?.textContent);

      if (!/^\d+/.test(periodText)) return;

      const period = parsePeriods(periodText);

      for (let columnIndex = 1; columnIndex <= 7; columnIndex++) {
        const cell = row.cells[columnIndex];
        if (!cell) continue;

        const detailDivs = Array.from(cell.querySelectorAll("div.kbcontent"))
          .filter(hasCourseContent);

        const summaryDivs = Array.from(cell.querySelectorAll("div.kbcontent1"))
          .filter(hasCourseContent);

        const divs = detailDivs.length > 0 ? detailDivs : summaryDivs;

        divs.forEach(div => {
          parseCourseDiv(div).forEach(course => {
            courses.push({
              name: course.name,
              location: course.location || "",
              teacher: course.teacher || "",
              weekText: course.weekText || "",
              weekInterval: course.weekInterval || [],
              weekday: weekdayMap[columnIndex - 1],
              weekdayName: weekdayNames[columnIndex - 1],
              period,
              periodText
            });
          });
        });
      }
    });

    return JSON.stringify({
      term: document.querySelector("#xnxq01id")?.value || "",
      courses
    });
  })();
